In [1]:
# 이제부터 Numpy에 대해 알아보자
# 여기서 부터는 약간의 코드와 함께 이해를 동반해야된다.

# 데이터 분석, 머신러닝, 딥러닝 이런 분야를 할때
# 가장 시간이 많이 걸리고 잘 해야되는게..
# 데이터 수집과 정제 

In [ ]:
# Numpy(Numerical Python)
# Pandas(데이터분석 모듈)와 matplotlib(시각화)의 
# basa가 되는 기본 자료구조를 제공

# Numpy는 딱 1개의 자료구조를 우리에게 제공한다.
#ndarray 자료구조를 제공
# n-dimensional(다 차원) array
# 보다 적은 메모리를 필요로하고 훨씬 더 빠른 처리를 할 수 있다!


In [13]:
# numpy는 외부 module이기 때문에 당연히 해당 모듈을 설치 해야된다.
# conda install numpy
# 설치했으면 그냥 막 쓸 수 있는가?
import numpy as np # import를 해야지만 사용할 수 있다.

a=[1,2,3,4,5] # python의 list
print(a) #[1, 2, 3, 4, 5]

b = np.array([1,2,3,4,5])
print(b) #[1 2 3 4 5]
print(type(b)) #<class 'numpy.ndarray'>
# 기억해야 하는 특징이 있다.
# list안에는 아무거나 막 들어올 수 있다.
c=[1,3.14,'홍길동',True]
# ndarray는 반드시 같은 데이터타입 끼리만 들어올 수 있다!!!
d = np.array([1,2,3.14,4,5])

print(d) #[1.   2.   3.14 4.   5.  ]
print(d.dtype) #dtype = data type의 약자, float64

[1, 2, 3, 4, 5]
[1 2 3 4 5]
<class 'numpy.ndarray'>
[1.   2.   3.14 4.   5.  ]
float64


In [4]:
# ndarray가 list와 가장 크게 차이가 나는건..
# 차원을 표현할 수 있다는 거다.

import numpy as np # 위에서 했기 때문에 두번 작성은 안해도 된다. 교수님 따라 코드의 완정성을 위해 적어줌

myList = [[1,2,3,],[4,5,6]] # 중첩리스트
# print(myList) #[[1, 2, 3], [4, 5, 6]]
arr = np.array(myList)
print(arr) #[[1 2 3]
             #[4 5 6]]
print(arr[0,1]) # print(arr[0][1]) 두개 결과값 2로 동일하다. 특별한 이유가 없는한 이게 정석
print(arr[0]) # arr가 가지고 있는 0번째 행 전부를 말한다.(1차원 numpy array),[1 2 3]
print(arr[0][1]) #2

[[1 2 3]
 [4 5 6]]
2
[1 2 3]
2


In [6]:
# 중요한 속성이 있다

# 1차원 ndarray를 하나 만들어 보자.
arr = np.array([1,2,3,4])
print(arr) #[1 2 3 4]
print(arr.dtype) #int64
print(arr.ndim) #n = 숫자, dim = 몇 차원인가? 를 나타낸다 , 1차원
print(arr.shape) # 어디에서나 나온다. shape 는 차원의 수와 요소의 개수를 같이 tuple로 표현한다.
# (4,) 튜플의 원소 개수는 차원수이고 각 차원의 숫자는 해당 차원의 요소수
# (4,) 에서 4는 1차원에 데 이터가 4개 있다는 의미다. 

b = [[1,2],[3,4],[5,6]]
arr = np.array(b)
print(arr.shape) #(3,2) 3= 행이 3개 있다는 의미, 2= 열이 2개 라는 의미

[1 2 3 4]
int64
1
(4,)
(3, 2)


In [17]:
# 데이터 표현부터 알아보자

#Python의 list
a = 10 # Scalar 0차원에서 1차원으로 올라가면 Scalar가 여러 개 있는 거다. 
b = [10,20,30] # 1차원 , Scalar를 여러개 놓기 위해 리스트로 표현 (vector)
c = [[1,2,3],[4,5,6]] # 2차원, 여러개의 1차원 리스트를 하나의 리스트로 묶는 형태 (matrix-행렬) 
d = [[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]] # 3차원, 여러 개의 2차원 리스트를 하나의 리스트로 묶어 놓은 형태(이미지 데이터가 대부분 3차원 형태))
#(4차원 :하나 이상의 이미지 형태들을 표현할 때 사용)
#계속해서 차원을 하나의 리스트로 묶어 나가면 차원이 높아진다.

#numpy의 ndarray
# arr = np.array(b) # 1차원
# print(arr)
# arr = np.array(c) # 2차원
# print(arr)
arr = np.array(d) # 3차원
print(arr)
print(arr.shape) # (2, 2, 3) 행이 2개 , 열이 2개, 원소의 개수 3개

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
(2, 2, 3)


In [21]:
# ndarray를 만드는 가장 쉬운 방법
#np.array()를 이용해서 만들었다.

# 다르게 만드는 방법도 있다.
# shape는 tuple로 표현

arr = np.zeros((3,4))
print(arr)

arr = np.arange(0,10,2)
print(arr)

# 주의해야 할건 .. python의 range()는 개념이다. 실제 데이터를 메모리에 가지고 있지 않는다.
#numpy의 arange()는 실제데이터를 가지고 있다!

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[0 2 4 6 8]


In [36]:
arr = np.arange(0,12,1) # 0을 포함해 12전까지 개수이므로 12개의 요소가 만들어진다.
# print(arr) # 1차원 ndarray 출력, [ 0  1  2  3  4  5  6  7  8  9 10 11]

# arr1 = arr.reshape(3,4) # 내가 원하는 형태의 차원으로 바꿔줄 수 있다. 
# print(arr1) #[[ 0  1  2  3]
#              #[ 4  5  6  7]
#              #[ 8  9 10 11]] 
        
# arr[-1] = 100
# print(arr) # [  0   1   2   3   4   5   6   7   8   9  10 100]

# print(arr1) #[[  0   1   2   3]
#              #[  4   5   6   7]
#              #[  8   9  10 100]]
#         #reshape는 1차원의 데이터를 바꾸면 2차원의 데이터도 바뀐다. reshape을 하면 view가 만들어진다.
#         #reshape는 데이터를 가지고 있기 때문에 이런 현상이 발생하는 것이다.

# arr2 = arr.reshape(2,2,3)
# print(arr2) #3차원 # [[[  0   1   2] 
                    #[  3   4   5]]

                 #[[  6   7   8]
                  #[  9  10 100]]]
            
# arr1 = arr.reshape(-1,2) 이 문장이 가능한데 -1의 의미는 상관하지 않겠다는 의미이며, 나머지가 다 들어간다.
arr1 = arr.reshape(-1,2)
print(arr1) 

arr2 = arr.reshape(3,-1)
print(arr2)

arr3 = arr.reshape(-1,-1,2) # 이건 결정이 덜 났다고 판단되어 오류가 발생한다.

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


ValueError: can only specify one unknown dimension

In [48]:
# numpy array가 있으면...
# 당연히 indexing과 slicing을 할 수 있다.

arr = np.arange(0,5,1)
print(arr) # [0 1 2 3 4]
print(arr[-1]) # 4

print(arr[0:2])  # [0 1]
print(arr[2:-1]) # [2 3]
print(arr[0: :2]) # 0부터 맨 끝까지 :2로 설정한 2칸씩 넘어가라는 뜻데로 작동한다. 가운데가 없는 이유는 끝까지 가라는 의미 [0 2 4]

arr = np.arange(1,17,1).reshape(4,4)
print(arr)
print(arr[1,2]) # 7
print(arr[1,2:4]) # [7 8]
print(arr[:,2]) # [ 3  7 11 15] 앞의 : 는 처음부터 끝까지의 모든 행 이라는 의미이고 , 2는 행의 3번째 자리 0,1,2 순서이기 때문에 

[0 1 2 3 4]
4
[0 1]
[2 3]
[0 2 4]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
7
[7 8]
[ 3  7 11 15]


In [52]:
# 기본 indexing과 slicing은 간단하다. python과 동일
# indexing에는 특이한 indexing기법이 두개가 더 있는데
# Boolean indexing은 기본적으로 boolean_mask를 이용해서 indexing하는 기법
# boolean indexing은 데이터 중에 내가 원하는 조건을 가지는 데이터를 추출하는 용도로 사용

arr = np.arange(0,5,1)
print(arr)

# boolean_mask는 내가 적용하는 ndarray와 shape가 같아야 한다.
boolean_mask = np.array([True,False,True,True,False])

print(arr[boolean_mask])



[0 1 2 3 4]
[0 2 3]


In [56]:
arr = np.array([1,2,3,4,5])
print(arr)

arr1 = np.array([10,20,30,40,50])
print(arr1)

print(arr + arr1)

arr = np.array([1,2,3,4,5])
print(arr)

arr1 = np.array([5,4,3,2,1])
print(arr1)

print(arr > arr1)

[1 2 3 4 5]
[10 20 30 40 50]
[11 22 33 44 55]
[1 2 3 4 5]
[5 4 3 2 1]
[False False False  True  True]


In [63]:
# 짝수만 뽑아봐라
arr = np.arange(0,10,1)
print(arr)

boolean_mask = np.array([True,False,True,False,True,False,True,False,True,False])
print(arr[boolean_mask]) # [0 2 4 6 8]

# arr % 2 == 0 # 2로 나눈 나머지 결과값 array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])
# 비교값을 줘서 해결
arr[arr % 2 == 0 ]
print(arr[arr % 2 == 0 ]) # [0 2 4 6 8]

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[0 2 4 6 8]


In [66]:
# 또 다른 indexing 방법 - Fancy indexing

arr = np.arange(0,12,1).reshape(3,4).copy()
print(arr)

# print(arr[2,2]) #10 Scalar
# print(arr[1:2,2]) # [6] vector
# print(arr[1:2,1:2]) # [[5]] matrix

print(arr[:2,[0,2]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 2]
 [4 6]]


In [67]:
# 기본적인 indexing
# 기본적인 slicing
# Boolean Indexing
# Fancy Indexing
# 에 대해서 알아보았다.

In [77]:
# ndarray의 연산!

arr = np.array([[1,2,3],[4,5,6]])
print(arr)
arr1 = np.arange(1,7,1).reshape(3,2)
arr2 = np.arange(1,7,1).reshape(2,3)
print(arr1)
print(arr2)

# print(arr +arr1) # 결과값의 같은 위치의 연산값이 다르기 때문에 오류가 난다. 같은 위치여야지만 하기 때문에 shape이 같아야한다 
print(arr +arr2) # 사칙연산이 가능하려면 shape(모양)이 같아야한다.

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]
[[ 2  4  6]
 [ 8 10 12]]


In [86]:
# arr = np.array([1,2,3,4,5])
# print(arr)

# arr + 3 # 원래는 shape이 다르기 때문에 에러가 나와야 정상이지만 넘파이가 어떻게든 수행시킬려고 한다. 
# #numpy가 형태를 맞추기 위해 3을 차원을 올리고 3을 복사한다. [3,3,3,3,3] 
# # 이를 scalar 3에 대해 broadcasting한다고 한다.
# print(arr + 3)

arr = np.arange(0,6,1).reshape(2,3)
arr1 = np.array([1,2,3])
# print(arr + 3)
print(arr)
print(arr1)
print(arr +arr1)


[[0 1 2]
 [3 4 5]]
[1 2 3]
[[1 3 5]
 [4 6 8]]


In [89]:
# 행렬곱연산은 어떻게 하나?

arr1= np.array([[1,2],[3,4],[5,6]])
print(arr1)
arr2 = np.array([[1,2],[3,4]])
print(arr2)

#행렬곱 연산을 해보자
print(np.dot(arr1,arr2)) # 결과값보다는 이런 결과를 도출할 수 있다는 것이 중요!

[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]]
[[ 7 10]
 [15 22]
 [23 34]]


In [104]:
# 집계함수와 축!

arr = np.arange(1,6,1)
print(arr)
print(arr.sum())  # 산술합계 구하는방법
print(arr.mean()) # 산술평균 구하는방법
print(arr.max())  # 최대값 구하는방법
print(arr.min())  # 최소값 구하는방법
print(arr.argmax()) # 가장 큰 값의 index를 알아내는 방법, 필요없어보이지만 필요하다.

#축의 개념이 나온다 ! axis
# 1차원 ndarray는 당연히 축이 1개이고 이걸 숫자로 표현한다.
# 숫자로 어떻게 표현하는가? 0부터 표현
print(arr.sum(axis=0)) # 1차원에서 x축 방향으로 다 더하라는 의미 
# print(arr.sum(axis=1)) # 1차원에서 축값을 다른것을 주게 되면 error가 발생히여 쓰지 못한다. 


arr = np.arange(1,7,1).reshape(2,3)
print(arr)
print(arr.sum()) # 몽땅 더한다.
# 2차원인 경우에는 축이 2개이다.
# 행 방향이란 행이 증가하는 방향이다. 열 방향이란 열이 증가하는 방향이다.
# 숫자 0 방향이 차원에 따라 바뀌므로 구분해야된다.
# 1차원에서 0방향은 행방향, 2차원에서는 열방향, 3차원에서는 면방향이다. 

#2차원
print(arr.sum(axis=0)) #열뱡향이므로 밑으로 더한다.
print(arr.sum(axis=1)) # 행방향이므로 옆으로 더한다. 

[1 2 3 4 5]
15
3.0
5
1
4
15
[[1 2 3]
 [4 5 6]]
21
[5 7 9]
[ 6 15]


In [107]:
# 10보다 큰 값의 합을 구하시오
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

print(arr>10) # 결과를 True 와 False로 볼 수 있다.

print(arr[arr>10].sum())


[[False False False False]
 [False False False False]
 [False False  True  True]
 [ True  True  True  True]]
81
